pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'OpenYurt - Home'
   keywords: 'OpenYurt'
   description: '一个原生kubernetes延伸到边缘的智能开放平台'
  # home config
  en-us:
   title: 'OpenYurt - Home'
   keywords: 'OpenYurt'
   description: 'OpenYurt'
 community:
  # 社区页配置
  zh-cn:
   title: 'OpenYurt - Community'
   keywords: 'OpenYurt'
   description: '一个原生kubernetes延伸到边缘的智能开放平台'
  # community page config
  en-us:
   title: 'OpenYurt - Community'
   keywords: 'OpenYurt'
   description: 'OpenYurt'
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'OpenYurt - Blog'
   keywords: 'OpenYurt'
   description: '一个原生kubernetes延伸到边缘的智能开放平台'
  en-us:
   # blog list page config
   title: 'OpenYurt - Blog'
   keywords: 'OpenYurt'
   description: 'OpenYurt'